package com.aries.blog.model;
// Generated May 5, 2015 4:48:35 PM by Hibernate Tools 3.6.0



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String name;
     private String password;
     private boolean enable;

    public User() {
    }

    public User(String username, String name, String password, boolean enable) {
       this.username = username;
       this.name = name;
       this.password = password;
       this.enable = enable;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEnable() {
        return this.enable;
    }
    
    public void setEnable(boolean enable) {
        this.enable = enable;
    }




}


