package br.cefetrj.sca.dominio;

public enum EnumSituacaoAvaliacao {
	APROVADO, REPROVADO_POR_MEDIA, REPROVADO_POR_FALTAS, TRANCAMENTO_DISCIPLINA, ISENTO_POR_TRANSFERENCIA, INDEFINIDA, TRANCAMENTO_TOTAL, APROVEITAMENTO_CREDITOS, ISENTO, APROVEITAMENTO_POR_ESTUDOS, MATRICULA, REPROVADO_SEM_NOTA, APROVADO_SEM_NOTA, REAPROVADO_COM_DEPENDENCIA;
}
